---

- name: "ossec_server | amazon | Add Atomiccorp OSSEC repo"
  yum_repository:
    name: atomic
    description: Atomicorp Amazon Linux - atomic
    gpgkey: "{{ ossec_server_gpg_key_url }}"
    mirrorlist: "{{ ossec_server_distro_vars[ansible_distribution|lower]['mirror_list'] }}"
  tags: ['ossec-server']

- name: "ossec_server | amazon | remove ossec agent if installed"
  yum: name="ossec-hids-agent" state="absent"
  when: ossec_server_uninstall_agent
  tags: ['ossec-server']

- name: "ossec_server | amazon | ensure ossec packages are installed"
  yum: name="{{ ossec_server_distro_vars[ansible_distribution|lower]['packages'] }}" state="present"
  tags: ['ossec-server']

- name: "ossec_server | amazon | Set ossec deploy facts"
  set_fact:
    ossec_server_config_filename: ossec-server.conf
    ossec_server_service_name: ossec-hids
    ossec_server_authd_service_name: ossec-hids-authd
  tags: ['ossec-server']
