---
- name: "ossec_server | centos | Set RHEL to expected name"
  set_fact:
    ansible_distribution: "rhel"
  when: ansible_distribution == "RedHat" or ansible_distribution == 'Red Hat Enterprise Linux'
  tags: ['ossec-server']

- name: "ossec_server | centos | Add Atomiccorp OSSEC repo"
  yum_repository:
    name: "atomic"
    description: "Atomicorp {{ ansible_distribution }} - atomic"
    gpgkey: "{{ ossec_server_gpg_key_url }}"
    mirrorlist: "{{ ossec_server_distro_vars[ansible_distribution|lower]['mirror_list'] }}"
  tags: ['ossec-server']

- name: "ossec_server | centos | Add EPEL repo (CentOS/RedHat 7)"
  yum:
    name: "epel-release"
    state: "present"
  when: ansible_distribution_major_version == "7"
  tags: ['ossec-server']

- name: "ossec_server | centos | Add EPEL repo (CentOS/RedHat 8)"
  dnf:
    name: epel-release
    state: latest
    update_cache: yes
  when: ansible_distribution_major_version == "8"
  tags: ['ossec-server']

- name: "ossec_server | centos | remove ossec agent if installed"
  yum: name="ossec-hids-agent" state="absent"
  when: ossec_server_uninstall_agent
  tags: ['ossec-server']

- name: "ossec_server | centos | ensure ossec packages are installed"
  yum: name="{{ ossec_server_distro_vars[ansible_distribution|lower]['packages'] }}" state="present"
  tags: ['ossec-server']
