---
- name: Converge
  hosts: all
  vars:
    ossec_server_config:
      mail_to:
        - noone@rhythmic.net
      mail_smtp_server: localhost
      mail_from: noreply@rhythmic.net
      frequency_check: 604800
      directories:
        - check_all: 'yes'
          dirs: /etc,/usr/bin,/usr/sbin
        - check_all: 'yes'
          dirs: /bin,/sbin
      localfiles:
        - format: 'syslog'
          location: '/var/log/syslog'
        - format: 'syslog'
          location: '/var/log/auth.log'
      globals:
        - '127.0.0.1'
      connection: 'secure'
      log_level: 1
      email_level: 7
      ignore_files:
        - /etc/mtab
        - /etc/mnttab
        - /etc/hosts.deny
    ossec_agent_configs:
      - type: os
        type_value: linux
        frequency_check: 79200
        ignore_files:
          - /etc/mtab
          - /etc/mnttab
          - /etc/hosts.deny
          - /etc/mail/statistics
          - /etc/svc/volatile
        directories:
          - check_all: 'yes'
            dirs: /etc,/usr/bin,/usr/sbin
          - check_all: 'yes'
            dirs: /bin,/sbin
        localfiles:
          - format: 'syslog'
            location: '/var/log/syslog'
          - format: 'syslog'
            location: '/var/log/auth.log'
          - format: 'syslog'
            location: '/var/log/mail.log'
  tasks:
    - include_role:
        name: "ansible-role-ossec-server"
